// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQag8iaAX6RYw84ADr5fu-57mQS1-8DY',
    appId: '1:335170233699:web:48e7758490c25294541f56',
    messagingSenderId: '335170233699',
    projectId: 'login-medico-fdbc0',
    authDomain: 'login-medico-fdbc0.firebaseapp.com',
    storageBucket: 'login-medico-fdbc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9B0AxFregz5NobCdbQR1egbsh_JbzZg4',
    appId: '1:335170233699:android:5937c4347eba956d541f56',
    messagingSenderId: '335170233699',
    projectId: 'login-medico-fdbc0',
    storageBucket: 'login-medico-fdbc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfWwFxa4eyfRBpvha3fN0tSNpka9z43Vo',
    appId: '1:335170233699:ios:c30f4b4d7f5f6689541f56',
    messagingSenderId: '335170233699',
    projectId: 'login-medico-fdbc0',
    storageBucket: 'login-medico-fdbc0.firebasestorage.app',
    iosBundleId: 'com.example.loginMedico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfWwFxa4eyfRBpvha3fN0tSNpka9z43Vo',
    appId: '1:335170233699:ios:c30f4b4d7f5f6689541f56',
    messagingSenderId: '335170233699',
    projectId: 'login-medico-fdbc0',
    storageBucket: 'login-medico-fdbc0.firebasestorage.app',
    iosBundleId: 'com.example.loginMedico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsQag8iaAX6RYw84ADr5fu-57mQS1-8DY',
    appId: '1:335170233699:web:07fc674f46fef79d541f56',
    messagingSenderId: '335170233699',
    projectId: 'login-medico-fdbc0',
    authDomain: 'login-medico-fdbc0.firebaseapp.com',
    storageBucket: 'login-medico-fdbc0.firebasestorage.app',
  );
}
